apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
schedulerName: sample-scheduler
leaderElection:
  leaderElect: true
  lockObjectName: sample-scheduler
  lockObjectNamespace: kube-system
plugins:
  preFilter:
    enabled:
    - name: "sample-plugin"
  filter:
    enabled:
    - name: "sample-plugin"
  preBind:
    enabled:
    - name: "sample-plugin"
pluginConfig:
- name: "sample-plugin"
  args:
    favorite_color: "#326CE5"
    favorite_number: 7