apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-orderbook
spec:
  accessModes:
  # 需要使用和 PV 一致的访问模式
  - ReadWriteMany
  # 按需分配资源
  resources:
      requests:
        storage: 40Gi
